### ISSUE TITLE
VS2019 locks up when saving a change on a file outside of the project that has the nuget

### ISSUE THREAD

**Issue by JohnH-FF** [OYIon/LiveSharp#33]
Using VS 16.2.1, LiveSharp nuget 1.0.66 installed in 1 of my projects.
Making code changes to the pages in this project work almost perfectly and I can see updates across UWP, iOS and Droid, all at the same time. Awesome stuff! Although it only works for me when I have a seperate method to build the UI and don't do it in the page constructor.

However, I have another project that contains UI view builders that I have created. When making a change to one of those builders (which is used by the pages mentioned above) at runtime, VS locks up and I have to force close.

Are there any debug options or switches I can use to provide more info?

Thanks
John

**Comment by ionoy** [comment]
Hello @JohnH-FF 

LiveSharp has now moved from VS extension to an external app. You will need to uninstall the extension, install app from https://github.com/OYIon/LiveSharp/releases and update NuGet package. This will definitely fix VS freezing issue since you won't even need a running VS instance anymore :)
